server:
  port: 8080


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      url: jdbc:mysql://121.196.151.249:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&charsetEncoding=utf8
      max-active: 8


mybatis-plus:
  # 默认是 classpath：mapper/**/*.xml
  mapper-locations: classpath：mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0